apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default
  labels:
    app: enmasse
spec:
  version: "0.27-SNAPSHOT"
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 2Gi
      storage: 5Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
